-- Dropt the talbe
DROP TABLE episodeIV;

-- For Eisode IV

CREATE TABLE episodeIV (name STRING, line STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' TBLPROPERTIES ("skip.header.line.count"="2");
LOAD DATA LOCAL INPATH '/root/input/episodeIV_dialouges.txt' INTO TABLE episodeIV;
SELECT name, COUNT(name) AS no_of_lines from episodeIV GROUP BY name ORDER BY no_of_lines DESC;

-- Display data from the table episodeIV

SELECT COUNT(*) FROM episodeIV WHERE INSTR(line, 'Luke')>0;
